### ISSUE TITLE
Include Rest Client 1.3

### ISSUE THREAD

**Issue by kwsutter** [eclipse/microprofile#101]
As Rest Client 1.3 makes progress, update the MicroProfile pom.xml file with the appropriate dependency information. This issue will be used to track the progress of including Rest Client 1.3.

**Comment by kwsutter** [comment]
Expected updates for each component are to the top-level microprofile pom.xml and the associated spec documents in the src/main/asciidoc directory:  architecture.asciidoc and required-apis.asciidoc.  Thanks!

**Comment by andymc12** [comment]
Update to the pom.xml should be to replace `<rest-client-version>1.3.1</rest-client-version>` in order to get the latest micro release.

**Comment by WhiteCat22** [comment]
PR: https://github.com/eclipse/microprofile/pull/110

**Comment by kwsutter** [comment]
FYI, we don't reference the Component's service/patch release for inclusion in the Platform release.  Thus, the Platform release will be pulling in Rest Client 1.3 from an API perspective.  This is consistent with the approach we took with OpenAPI a couple of releases back.  They had an updated 1.1.1 release, but the referenced release for the Platform was 1.1.  I'm making the updates to expedite the changes.  I'll be producing an RC1 soon, so we can discuss it further there.  Thanks!

**Comment by andymc12** [comment]
Looks like the `1.3.1` -> `1.3` change was made in:
https://github.com/eclipse/microprofile/commit/aea6b64aef1908f6937da3df6364d7d8c2360407

I think this is good to close now.  Thanks!
