### ISSUE TITLE
JDK 11

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile#103]
Should we consider switching all components to build with JDK 11 for MicroProfile 3.0, and specifying that it runs on JDK 11?

If there are invasive changes required, it's a good time to do it with the breaking change release.

**Comment by kenfinnigan** [comment]
FYI @andymc12

**Comment by smillidge** [comment]
Build JDK 11 compiled jars that can't run on JDK 8 or just jars that run on JDK 11 and JDK 8?

This first will require all runtimes to run on JDK 11. However the baseline for the underlying Java EE 8 components is JDK 8.

**Comment by kenfinnigan** [comment]
We could take either approach.

But we need to consider that JDK 8 is no longer supported commercially without a separate agreement.

**Comment by GedMarc** [comment]
You can go a much better route while still keeping JDK 8 compatibility - 

The goal is to be able to distribute JLink distributions, which require that all libraries be JPMS fully compatible, aka have a module-info class in either the root or the versions/ directory placement.

Current standard is to use moditect to build the module info file. 

There is no need to break JDK 8 building for 100% JPMS compatibility, but there needs to be, acceptance, that we no longer look at backwards compatible, but forwards acceptable.

**Comment by kenfinnigan** [comment]
@GedMarc I'm not quite sure what you're suggesting

**Comment by smillidge** [comment]
I don't see why we would break JDK 8 compatibility to deliver MP 3.0. Are there specific JDK 11 only features that are being introduced in the 3.0?

**Comment by kenfinnigan** [comment]
I don't believe so, it's more a recognition that the JDK has moved on and we need to be mindful of what JDK support customers are able to have going forward

**Comment by smillidge** [comment]
Of course it should run on JDK 11 however it shouldn't mandate JDK 11 there's a big difference.

**Comment by kenfinnigan** [comment]
That's why I said we could take either approach right now, but there will come a point where we need to drop JDK 8

**Comment by GedMarc** [comment]
@kenfinnigan To rather keep JDK 8 for now while people migrate across to JPMS and JLink (As different to JDK 11/Classpath Mode) by using a module-info generator such as @moditect, 

This will satisfy all requirements for JPMS, as well as keep support for JDK 8 while moving across/allowing time to move across.

As the chosen path for most current up to date libraries I think it should be a proper consideration xD But I'm just the peon :)

**Comment by kenfinnigan** [comment]
Thanks for clarification @GedMarc

**Comment by anthonyvdotbe** [comment]
If/when Reactive Streams Operators (RSO) is added to the platform, JDK 11 should be required, such that RSO can be updated to use JDK 9's `java.util.concurrent.Flow` API instead of the original Reactive Streams API

**Comment by kenfinnigan** [comment]
Closing in favor of splitting this out into two issues, as there are two separate steps we can take:

https://github.com/eclipse/microprofile/issues/106
https://github.com/eclipse/microprofile/issues/107
