### ISSUE TITLE
Tracking release 3.0

### ISSUE THREAD

**Issue by pavolloffay** [eclipse/microprofile#105]
I am creating a tracking issue for release 3.0 https://github.com/eclipse/microprofile/milestone/2.

@kwsutter what is the last date individual specs should be released to be included in 3.0?

**Comment by kenfinnigan** [comment]
Do we need an issue if we have a milestone?

**Comment by pavolloffay** [comment]
I find it useful, people cannot subscribe to a milestone or comment on it. Here you can do both and notify users on changes.

**Comment by pavolloffay** [comment]
@kenfinnigan you know what is the expected date to have prepared specs to be included in MP 3.0? 
Initially we didn't want to include OT in the 3.0, I hope it's not a problem to include it.

**Comment by kenfinnigan** [comment]
I think RCs need to be done by mid May

**Comment by Emily-Jiang** [comment]
I think final release need to be done by Mid May as the release date of MP 3.0 is 5th June as marked now. I would start working on RC asap.

**Comment by kwsutter** [comment]
Sorry, missed this ping...  The individual component releases need to be completed by **May 15** (https://calendar.google.com/calendar/embed?src=gbnbc373ga40n0tvbl88nkc3r4@group.calendar.google.com&pli=1).

**Comment by kwsutter** [comment]
I think this Issue can now be closed...
