### ISSUE TITLE
Standarise the way to publish releases

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile#122]
Since spec html and pdf are not in maven central. In the past, the pdfs and htmls are attached to the releases. However, it is not convenient as they have to be downloaded for viewing. 

In the recent release architecture changes, all of the docs and javadocs are uploaded to [here](https://download.eclipse.org/microprofile/). When releasing MicroProfile reactive messaging, I used the following [format](https://github.com/eclipse/microprofile-reactive-messaging/releases/), which is much more user friendly.

I updated MicroProfile config to use this format. All other specs should adopt this format for improvement.

We also need to update microprofile.io to list all spec/pdf. I've filed [this](https://github.com/microprofile/microprofile-site/issues/87) issue on microprofile-site repo.

**Comment by OndroMih** [comment]
Ideally, the Jenkins release job would use GitHub API to generate the description for the release, including links to Javadocs and spec documents and info about the maven artifact.

**Comment by Emily-Jiang** [comment]
done
