### ISSUE TITLE
Create a MicroProfile parent pom

### ISSUE THREAD

**Issue by jeanouii** [eclipse/microprofile#123]
Most specifications have a parent pom which is an aggregator for API, TCK, SPEC (at least).
Pretty much all of them have checkstyle rules, rat, gpg (release profile, etc).

We could make projects life easier if we created a MicroProfile parent pom with that.
We could also add configuration to build HTML/PDF spec docs and attach them to the binaries on Maven.

That could also help https://github.com/eclipse/microprofile/issues/122

**Comment by cchacin** [comment]
@jeanouii @kenfinnigan I would like to contribute with this if no other volunteers so far

**Comment by kenfinnigan** [comment]
The main item to be discussed with this at present is whether everyone is in agreement that a parent pom is needed.

In the past, it's been a 50/50 split, which is why nothing has happened to date.
