### ISSUE TITLE
Make OSGi dependency provided

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile#125]
As per https://github.com/eclipse/microprofile-config/issues/368, we should mark the OSGi dependency as provided as it's not needed for runtime usage.

**Comment by kenfinnigan** [comment]
Agreed in today's MP Arch call that this should be done across all specs

**Comment by kenfinnigan** [comment]
Remaining issues:

- https://github.com/eclipse/microprofile-reactive-streams-operators/issues/132
- https://github.com/eclipse/microprofile-fault-tolerance/issues/494
- https://github.com/eclipse/microprofile-reactive-messaging/issues/88
- https://github.com/eclipse/microprofile-opentracing/issues/164
- https://github.com/eclipse/microprofile-jwt-auth/issues/144
- https://github.com/eclipse/microprofile-open-api/issues/400

**Comment by Emily-Jiang** [comment]
done
