### ISSUE TITLE
Include OpenAPI 1.2

### ISSUE THREAD

**Issue by xstefank** [eclipse/microprofile#152]
[no MicroProfile OpenAPI 1.2 milestone available]
[MicroProfile OpenAPI 1.2 diff](https://github.com/eclipse/microprofile-open-api/compare/mp-openapi-1.1...master)

**Comment by arthurdm** [comment]
hi @xstefank - the latest version of MP OpenAPI is 1.1.2 (https://github.com/eclipse/microprofile-open-api/releases)

**Comment by xstefank** [comment]
Hi @arthurdm. This issue is for the required update (which I believe must be a minor) required because of https://github.com/eclipse/microprofile-open-api/issues/383. If I'm wrong, correct this issue, please.

**Comment by fabiobrz** [comment]
Hi @xstefank and @arthurdm. I've been reading of recent updates about what is going to change regarding OpenAPI spec, e.g. see [1] and [2].

Can you please provide some basic detail on the differences OpenAPI when switching from MP 3.2 to MP 3.3? Thanks.

[1]
https://github.com/eclipse/microprofile-open-api/issues/383#issuecomment-571772302

[2]
https://github.com/eclipse/microprofile-open-api/issues/399#issuecomment-571751168

**Comment by xstefank** [comment]
@fabiobrz on yesterday's [MP hangout](https://docs.google.com/document/d/16v3jVkcDzVz9BVU5aGEzPVbK-a8BIx7S1gbqToVUaLs/edit#bookmark=id.go4e619czr4s) it was decided that we will postpone Jakarta EE 8 to June release (MP 4.0). So basically this issue and OpenAPI release can be closed/postponed until then depending on whether there will be functional, **non-breaking** release of OpenAPI.

**Comment by fabiobrz** [comment]
> So basically this issue and OpenAPI release can be closed/postponed until then depending on whether there will be functional, non-breaking release of OpenAPI for MP 3.3 (Feb 2020).

Thanks @xstefank, my concern is to assess what is going to change for MP OpenAPI spec when moving Mp version from 3.2 to 3.3. IIUC your message, then there should be **non-breaking** changes, but what about new features/fixes? I am specifically looking at this from testing perspective.

**Comment by xstefank** [comment]
I leave this response to @arthurdm :)

**Comment by arthurdm** [comment]
Hey guys - since the Jakarta EE 8 update has been delayed to MP 4.0 we won't be doing a MP OpenAPI 1.2 release for MP 3.3.  We will instead release MP OpenAPI 2.0 to be included into MP 4.0.

Perhaps we can close this issue now?

**Comment by fabiobrz** [comment]
> Hey guys - since the Jakarta EE 8 update has been delayed to MP 4.0 we won't be doing a MP OpenAPI 1.2 release for MP 3.3. We will instead release MP OpenAPI 2.0 to be included into MP 4.0.

Thanks for your feedback @arthurdm!

**Comment by xstefank** [comment]
Closing as this upgrade will not be a part of MP 3.3.
