### ISSUE TITLE
Include JWT 1.2

### ISSUE THREAD

**Issue by xstefank** [eclipse/microprofile#153]
[no MicroProfile JWT 1.2 milestone available]
[MicroProfile JWT 1.2 diff](https://github.com/eclipse/microprofile-jwt-auth/compare/1.1...master)

**Comment by ederks85** [comment]
Please update the description to reference https://github.com/eclipse/microprofile-jwt-auth/issues/137

**Comment by ederks85** [comment]
Please update the description to include Milestone https://github.com/eclipse/microprofile-jwt-auth/pull/143

**Comment by xstefank** [comment]
@ederks85 I can't find the milestone for 1.2.

**Comment by xstefank** [comment]
Closing as this upgrade will not be a part of MP 3.3.
