### ISSUE TITLE
Include OpenTracing 1.4

### ISSUE THREAD

**Issue by xstefank** [eclipse/microprofile#154]
[MicroProfile OpenTracing 1.4 milestone](https://github.com/eclipse/microprofile-opentracing/milestone/5)
[MicroProfile OpenTracing 1.4 diff](https://github.com/eclipse/microprofile-opentracing/compare/1.3...master)

**Comment by xstefank** [comment]
@pavolloffay I'm not sure what the outcome of the OpenTelemetry inclusion is. Will there be also OpenTelemetry 1.0 in MP 3.3?

**Comment by kenfinnigan** [comment]
OpenTelemetry will not be part of MP 3.3

**Comment by pavolloffay** [comment]
@kenfinnigan @xstefank MP 1.4 was supposed to contain only update to Jakarta APIs, since this is not going to be pursued in MP 3.3 can we close this issue?

**Comment by xstefank** [comment]
@pavolloffay so OT 1.4 will be included in MP 3.3 right? Then we need to keep this open.

**Comment by kenfinnigan** [comment]
I agree this can be closed

**Comment by xstefank** [comment]
Closing as this will not be part of MP 3.3.
