### ISSUE TITLE
Include Reactive Messaging 1.1 (stand alone)

### ISSUE THREAD

**Issue by xstefank** [eclipse/microprofile#155]
[MicroProfile Reactive Messaging 1.1 milestone](https://github.com/eclipse/microprofile-reactive-messaging/milestone/1)
[MicroProfile Reactive Messaging 1.1 diff](https://github.com/eclipse/microprofile-reactive-messaging/compare/1.0...master)

**Comment by kenfinnigan** [comment]
Is this needed?

There's no relation between MP umbrella and standalone releases

**Comment by xstefank** [comment]
@kenfinnigan I asked @jclingan and he said we should also track stand alone releases. But of course, this should be discussed separately in the hangout. I personally like the visibility. Maybe we can just say that we don't care whether the standalone specs miss the deadlines?

**Comment by kenfinnigan** [comment]
I would say we don't care, as it doesn't matter when they release if they're not included.

+1 to raising a thread to discuss

**Comment by xstefank** [comment]
Maybe just raising an issue here without a milestone set would be a sufficient solution?

**Comment by kenfinnigan** [comment]
possibly, yes

**Comment by xstefank** [comment]
the mentioned google group thread - https://groups.google.com/forum/#!topic/microprofile/tHQ8AhXTYIE

**Comment by xstefank** [comment]
Closing for now as the resolution was not reached. Feel free to reopen if needed.
