### ISSUE TITLE
Mark all dependencies as "provided"

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile#158]

**Comment by ederks85** [comment]
I can make the changes

**Comment by kwsutter** [comment]
We need to determine if we're limiting this change to just the Platform pom, or if we need to push this down to all of the component poms as well.  I posted a comment like this to the PR #183 as well.

**Comment by ederks85** [comment]
Verifying provided scope dependencies in component specs:
- [ ] Config
- [ ] Fault Tolerance
- [ ] Health
- [ ] JWT
- [ ] Metrics
- [ ] Open API
- [ ] Rest Client
- [ ] OpenTracing

**Comment by ederks85** [comment]
@jclingan @kwsutter I have checked the component spec API builds; all contain 'jakarta.enterprise.*' dependencies on 'provided' scope

@kenfinnigan can you please close this issue? This one has been resolved

**Comment by jclingan** [comment]
Thx @ederks85 !!
