### ISSUE TITLE
Create MicroProfile level pom.xml for the sub project to inherit

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile#161]
At the moment, each spec has its own dependencies specified with various versions etc. This includes javadoc, checkstyle, jar signer etc. We are running out of sync. I think we need to put the common dependencies on the microprofile parent project and then subprojects inherit it. In this way, we don't need to go through more than 7 places to update the version or apply the same fixes over and over again.

**Comment by kenfinnigan** [comment]
Closing as duplicate of #123
