### ISSUE TITLE
Working Group Opportunity Phase

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile#172]
Opportunity Phase tracking according to the[ Working Group Process document](https://www.eclipse.org/org/workinggroups/process.php).

- [x] Working Group Sponsor identified - Paul Buck
- [x] Initial Lead Organization(s) Identified - IBM, Red Hat, Tomitribe
- [x] Initiation Agreement
- [x] Establish participant pipeline - IBM, Red Hat, Tomitribe
- [ ] [Working Group Charter Draft](https://docs.google.com/document/d/1cCMN298rUAX45Nq-ZJv755WZe8yVjyAo1Gz_wN8r7wc/edit) complete.
- [ ] Executive Director Approval

**Comment by Emily-Jiang** [comment]
done
