### ISSUE TITLE
Working Group Proposal Phase

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile#173]
Proposal Phase tracking according to the[ Working Group Process document](https://www.eclipse.org/org/workinggroups/process.php).

- [ ] [Initial Working Group Charter Published](https://docs.google.com/document/d/1cCMN298rUAX45Nq-ZJv755WZe8yVjyAo1Gz_wN8r7wc/edit).
- [ ] Three committed participants
- [x] Communication Infrastructure identified - [MicroProfile Google Group](https://groups.google.com/forum/#!forum/microprofile)
- [ ] Recruiting Materials created (Website, membership prospectus, membership flyer)
- [ ] Executive Director Approval

**Comment by jclingan** [comment]
Requires a membership prospectus #176

**Comment by jclingan** [comment]
Requires #176

**Comment by jclingan** [comment]
Requires #177 - create membershp flyer. We can discuss if we think this is really required. Can probably come later.

**Comment by jclingan** [comment]
Requires #178 - create working group website.

**Comment by Emily-Jiang** [comment]
done
