### ISSUE TITLE
Working Group Incubation Phase

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile#174]
Incubation Phase tracking according to the[ Working Group Process document](https://www.eclipse.org/org/workinggroups/process.php).

- [ ] [Final Working Group Charter Published](https://docs.google.com/document/d/1cCMN298rUAX45Nq-ZJv755WZe8yVjyAo1Gz_wN8r7wc/edit) complete.
- [ ] Minimum five committed participants
- [ ] Communication Infrastructure established
- [ ] Working Group committees operational
- [ ] Executive Director Approval

**Comment by Emily-Jiang** [comment]
done
