### ISSUE TITLE
Create Membership Prospectus

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile#176]
Extol the virtues of MicroProfile to prospective member. Examples: [GEMOC](http://gemoc.org/members.html), [IoT](https://iot.eclipse.org/membership/), [Jakarta EE](https://jakarta.ee/documents/membership/jakarta-ee-membership-prospectus.pdf), [Edge Native](https://edgenative.eclipse.org/about/faq/). There seems to be quite a bit of variance on how to convey membership value.

**Comment by jclingan** [comment]
Required for #173

**Comment by Emily-Jiang** [comment]
done
