### ISSUE TITLE
TCK compliance for MP 4.0

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile#191]
Use this issue to track down the discusson on MP umbrella release TCK compliance.

For compliance, we need to mandate all of the included TCKs should pass.

    MicroProfile Config 2.0

    MicroProfile Fault Tolerance 3.0

    MicroProfile Health 3.0

    MicroProfile JWT Authentication 1.2

    MicroProfile Metrics 3.0

    MicroProfile OpenAPI 2.0

    MicroProfile OpenTracing 2.0

    MicroProfile Rest Client 2.0

Jakarta EE specs

    Jakarta Contexts and Dependency Injection 2.0

    Jakarta Annotations 1.3

    Jakarta RESTful Web Services 2.1

    Jakarta JSON Binding 1.0

    Jakarta JSON Processing 1.1

This include Jakart EE specs: CDI, annotation, JAX-RS, JSON-P and JSON-B.

Since MP does not pull in EJB, a subset of CDI TCKs are to be executed, namely removing the tests with EJB and EL dependencies.

**Comment by radcortez** [comment]
Do we have set of instructions on how MP only implementation may run the Jakarta TCK's?

**Comment by mkouba** [comment]
> Since MP does not pull in EJB, a subset of CDI TCKs are to be executed, namely removing the tests with EJB and EL dependencies.

I don't think that it's enough. The CDI TCK also includes tests for integration with other technologies, such as JMS, JAX-WS, Servlets, EAR packaing, etc.
