### ISSUE TITLE
Dry Run - MicroProfile Config 2.0-RC9 - Specification Review

### ISSUE THREAD

**Issue by radcortez** [eclipse/microprofile#196]
- [x] Specification name and version
MicroProfile Config 2.0

- [x] Add a label from one of: creation, plan, progress, release
Releases

- [x] A link to a directory under https://download.eclipse.org/microprofile/staging in the form orgeclipsemicroprofile-NNN where NNN is the staging repository id assigned to the staged with the following:
   - [x] Specification PDF in the form of microprofile-_project_-spec.pdf where
_project_ is the microprofile specification short project name (config, health, ...)
   - [x] Specification HTML in the form of microprofile-_project_-spec.html
   - [x] An apidocs directory containing the javadoc associated with the API jar.
   - [x] A copy of the staged api jar, and TCK artifact

Instead of a link in the Eclipse downloads section the proposal is to use the Nexus Staging link which contains all the binaries and relevant documentation:
- [Staging Repo](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1357/org/eclipse/microprofile/config/)
  - [Spec PDF](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1357/org/eclipse/microprofile/config/microprofile-config-spec/2.0-RC9/microprofile-config-spec-2.0-RC9-pdf.pdf)
  - [Spec HTML](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1357/org/eclipse/microprofile/config/microprofile-config-spec/2.0-RC9/microprofile-config-spec-2.0-RC9-html.html)
  - [Javadoc](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1357/org/eclipse/microprofile/config/microprofile-config-api/2.0-RC9/microprofile-config-api-2.0-RC9-javadoc.jar)
  - [API Jar](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1357/org/eclipse/microprofile/config/microprofile-config-api/2.0-RC9/microprofile-config-api-2.0-RC9.jar)
  - [TCK Jar](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1357/org/eclipse/microprofile/config/microprofile-config-tck/2.0-RC9/microprofile-config-tck-2.0-RC9.jar)
<p>

A link in the Eclipse downloads sections is still available for specs and api-docs, but is not published anywhere:
https://download.eclipse.org/microprofile/microprofile-config-2.0-RC9/

- [ ] [Release Review](https://www.eclipse.org/projects/handbook/#release-review)
  - [x] Updated release record
    - [Release Record](https://projects.eclipse.org/projects/technology.microprofile/releases/config-2.0)
  - [ ] Email to PMC
  - [ ] Start release review by emailing EMO
  - [x] Summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification.
     - [Compatible Implementation Update API Config RC9](https://github.com/smallrye/smallrye-config/commit/5735f5c6bbeba268113a58b0c202916e9cb4b741)
     - [Compatible Implementation TCK Run](https://github.com/smallrye/smallrye-config/actions/runs/347738524)
     - [Compatible Implementation TCK Report](https://github.com/smallrye/smallrye-config/suites/1456312394/artifacts/24873416)

**Comment by radcortez** [comment]
This is just a Dry Run using the proposed template from https://github.com/eclipse/microprofile/pull/193. I know it is not approved yet, but I think we need to try it and adjust it with a real case to see how it goes.

**Comment by Emily-Jiang** [comment]
We have moved the issue to microprofile-wg.
