### ISSUE TITLE
Move release artifacts from staging to its parent

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile#199]
After the spec review completes, we need to move the artifacts from staging dir to its parents.
e.g. at the moment, the Config artifacts are under https://download.eclipse.org/microprofile/staging/microprofile-config-2.0/. They need to be moved to https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html

**Comment by xstefank** [comment]
This was resolved by creating a new Jenkins job [MicroProfile Post-Release](https://ci.eclipse.org/microprofile/view/Release/job/MicroProfile%20Post-Release/) that will do the move.
