### ISSUE TITLE
Rename "master" branch to "main"

### ISSUE THREAD

**Issue by kwsutter** [eclipse/microprofile#218]
Introduced on today's [MicroProfile Technical Call](https://docs.google.com/document/d/1Ou7mvxQdYjZJOkzvMmCAGvlYr04veQfvEyzW__CLrUU/edit#bookmark=kix.rn5zf51qew1).

It was decided we should create an issue for further discussion and possible future action.  

A few notes...
- This change does not provide any technical advantages.
- The main idea behind this change is to use more inclusive language.
- Going forward, all new Git repositories will be created with the "main" branch (vs "master).  This proposed change is to make us consistent with that direction. 
- This type of change does have some ripple effects to our build and CI infrastructure (jenkins, etc).

Please add any additional comments (pros and cons) to this Issue so that we can make an informed decision in the future.

**Comment by dblevins** [comment]
I think this is a no-brainer.  +1

**Comment by ederks85** [comment]
+0

I'm sorry but I would like to abstain. I have never understood how and why using inclusive language made it's way into this context of software development and that we are trying to solve a problem that isn't there in the first place (personal opinion). However, if this is how the world currently works and people find this important, I'm not going to prevent any progress in that regard.

**Comment by GedMarc** [comment]
+0
Common sense trumps emotional instability, also, there's a globe to consider, not just one countries murmurs or isolated events

**Comment by rdebusscher** [comment]
+0

Inclusive language/mindset is good and should be encouraged but I'm not convinced the name of the branch or the list (blacklist - whitelist) is the most important aspect in this discussion.

**Comment by kwsutter** [comment]
I'm still convinced that we should remove the concept of master/slave from our github repositories.  Since I will not be around to facilitate this change, I will leave you with this tweet...
https://twitter.com/nelsonsamd/status/1468240004463874058?t=hukYc9h5oCinPhB0kFelhQ&s=03

**Comment by Emily-Jiang** [comment]
done
