### ISSUE TITLE
MP 5.0 Jakarta EE 9.1 alignment

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile#223]
MP 5.0 will be the Jakarta EE 9.1 alignment without any other functional update from each MicroProfile Component specification. MP 5.0 will include the following MicroProfile component specifications:

- [x] [Config](https://github.com/eclipse/microprofile-config/issues/668)
- [x] [Fault Tolerance](https://github.com/eclipse/microprofile-fault-tolerance/issues/592)
- [x] [Metrics](https://github.com/eclipse/microprofile-metrics/issues/639)
- [x] [Health](https://github.com/eclipse/microprofile-health/issues/307)
- [x] [Open Tracing](https://github.com/eclipse/microprofile-opentracing/issues/219)
- [x] [Open API](https://github.com/eclipse/microprofile-open-api/issues/487)
- [x] [JWT](https://github.com/eclipse/microprofile-jwt-auth/issues/246)
- [x] [Rest Client](https://github.com/eclipse/microprofile-rest-client/issues/316)
### For each spec, the following updates need to happen, refer [this doc](https://docs.google.com/document/d/1bhhfmhxHJpQdmdUtQw5o_WtScpzkfHoTNGPvrQnGhc0/edit) for instructions:

- [ ] Create a branch called `jakarta91-branch` off master to perform Jakarta EE 9.1 alignment
- [ ] Only jakarta namespace changes are allowed in the release without any other functional changes with the exception of typos or tck fixes
- [ ] pom.xml: utilise microprofile-parent 2.1 as it has pulled in all of the Jakarta EE 9.1 as well as the necessary TCK dependencies (see [this](https://github.com/eclipse/microprofile-config/pull/663) PR on how to)
- [ ] spec docs: rename Java EE to Jakarta EE, rename javax to jakarta: `find . -type f -name '*.asciidoc' -exec sed -i '' s/javax./jakarta./ {} +`
- [ ] Update all javax to jakarta for all java files `import javax.*` needs to be updated to `jakarta.*`: `find . -type f -name '*.java' -exec sed -i '' s/javax./jakarta./ {} +`
- - [ ] TCKs
- - [ ] APIs

- [ ] Update bnd file:  `find . -type f -name ‘*.bnd' -exec sed -i '' s/javax./jakarta./ {} +`

- [ ] service loader file javax.* to jakarta.*: `find . -type f -name "javax*" -exec sh -c 'mv "$0" "${0/javax/jakarta}"' '{}' \;
`
- [ ] deliver the changes to both `jakarta91-branch` and `master`
- [ ] Perform a RC release off the branch `jakarta91-branch`

**Comment by Emily-Jiang** [comment]
Also created the following issues to track the standalone specs:

- [ ] [Context Propagation](https://github.com/eclipse/microprofile-context-propagation/issues/210)
- [ ] [Reactive Streams Operators](https://github.com/eclipse/microprofile-reactive-streams-operators/issues/169)
- [ ] [Reactive Messaging](https://github.com/eclipse/microprofile-reactive-messaging/issues/137)
- [ ] [GraphlQL](https://github.com/eclipse/microprofile-graphql/issues/386)
- [ ] [LRA](https://github.com/eclipse/microprofile-lra/issues/351)

**Comment by majidmostafavi** [comment]
Hello Emily 
I want to help with this issue. Please tell me what should I do.

**Comment by Emily-Jiang** [comment]
@majidmostafavi would you like to help with [Reactive Streams Operators](https://github.com/eclipse/microprofile-reactive-streams-operators/issues/169). Please go ahead to grab that issue and have a go with it.
