### ISSUE TITLE
Does microprofile support JDK 17?

### ISSUE THREAD

**Issue by pjgg** [eclipse/microprofile#225]
### Questions

Java 17 (LTS) will be released [soon](https://openjdk.java.net/projects/jdk/17/), do you know if microprofile is supported under this JDK version. 

Related to: https://github.com/eclipse/microprofile/issues/107

**Comment by Emily-Jiang** [comment]
MicroProfile provides APIs and they can run on JDK 17. As for the supporting of JDK 17 or not in the implementations, it depends on the implementations. I know Open Liberty is very keen and try to support JDK 17. I am not sure with other implementations. It will need some time for MicroProfile APIs to use JDK 17 features, it might need some time to wait for some use cases.

**Comment by RuiBaiXYZ** [comment]
Here is a reference.
Java 17 support and a number of significant bug fixes in Open Liberty 21.0.0.10
https://openliberty.io/blog/2021/10/01/java17-210010.html

**Comment by pjgg** [comment]
thank you @RuiBaiXYZ
