### ISSUE TITLE
[MP 5.0] Suggestion- Add the blog announcement Tag/5.0 & onwards

### ISSUE THREAD

**Issue by aeiras** [eclipse/microprofile#239]
What about we add to https://github.com/eclipse/microprofile/releases/tag/5.0 the MP blog announcement?
Doing so under description. 

@ederks85 @Emily-Jiang & @emecas WDYT?

**Comment by Emily-Jiang** [comment]
What do you mean the MP blog announcement?

**Comment by aeiras** [comment]
Hola Emily, 

This https://microprofile.io/2021/12/07/microprofile-5-0-release/
insert it here:
![image](https://user-images.githubusercontent.com/10731224/146074059-304273f2-20ce-4ee9-9c24-0e0d54b33c10.png)

**Comment by Emily-Jiang** [comment]
There is already a link to the release: see the hyperlink of MicroProfile 5.0.
MicroProfile, an Open-Source Community that collaborates on enterprise Java microservices, would like to announce the release of [MicroProfile 5.0](https://microprofile.io/2021/12/07/microprofile-5-0-release/).

**Comment by Emily-Jiang** [comment]
ah, I see. You want the description of https://microprofile.io/2021/12/07/microprofile-5-0-release/ to point to the blog. good idea. Go ahead to add it.

**Comment by aeiras** [comment]
Excellent, @Emily-Jiang!

I have added 2 cosmetic updates to https://github.com/eclipse/microprofile/releases/tag/5.0

Emily, can you please help update the marketing checklist git issue template? : 
[Issue: Platform Release Marketing Request](https://github.com/eclipse/microprofile-marketing/issues/new?assignees=&labels=platform+release+mareking+%3Abulb%3A&template=01-platform-release-marketing-request.md&title=)

I added the step into the tasks :) https://github.com/eclipse/microprofile-marketing/wiki/Marketing-Release-Process. 

Update MicroProfile presentation and save it in the right folder (technical person)
Import the presentation to the landing page and resources page of the website
Draft a release announcement blog post using a template (technical person)
Update MicroProfile homepage with release announcement design card
Edit/Publish release announcement blog post on the MicroProfile Blog
Add the blog link announcement to the https://github.com/eclipse/microprofile/releases description (committer)
Announce the release on social media using Hootsuite (Twitter, Linkedin, Facebook)
Write an update to the MP Community Forum about the release
Update the MP Calendar with the Release Date (committer)

Gracias!
