### ISSUE TITLE
Remove Payara's logo from MicroProfile's website

### ISSUE THREAD

**Issue by ZahraFazli** [eclipse/microprofile#244]
Payara is no longer part of the MicroProfile Working Group. Kindly remove their logo from the website: https://microprofile.io/
thanks!

**Comment by rdebusscher** [comment]
It is unclear what those logos mean. As there are logos from several other companies/organizations that are also not a member of the working group. (and they never were a member in the past)
But it isn't either a list of implementations of MicroProfile.

So before it can be decided if it needs to be removed, their must be a title indicating what the logos represent (Implementations, Working Group Members, supporters, ...)

**Comment by Emily-Jiang** [comment]
I believe this is done. see https://microprofile.io/
