### ISSUE TITLE
MicroProfile 4.1 Compatible Certification Request - Quarkus MicroProfile 2.7.2.Final

### ISSUE THREAD

**Issue by radcortez** [eclipse/microprofile#247]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
RedHat

- [x] Product Name, Version and download URL (if applicable):<br/>
[Quarkus MicroProfile 2.7.2.Final](https://github.com/quarkiverse/quarkus-microprofile)

- [x] Specification Name, Version and download URL:<br/>
MicroProfile 4.1

- [x] Public URL of TCK Results Summary:<br/>
https://github.com/quarkiverse/quarkus-microprofile/releases/download/2.7.2.Final/tck-results.html

With the following exceptions:
- org.eclipse.microprofile.fault.tolerance.tck.interceptor.xmlInterceptorEnabling.FaultToleranceInterceptorEnableByXmlTest
- org.eclipse.microprofile.rest.client.tck.cditests.HasConversationScopeTest
- org.eclipse.microprofile.rest.client.tck.cditests.HasSessionScopeTest

Due to:
- https://github.com/eclipse/microprofile-fault-tolerance/pull/596
- https://github.com/eclipse/microprofile-rest-client/issues/330 

- [x] Any Additional Specification Certification Requirements:<br/>
No

- [x] Java runtime used to run the implementation:<br/>
11

- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
GH Actions, Ubuntu

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).

- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.
With the exceptions detailed in the TCK Results Summary.

**Comment by Emily-Jiang** [comment]
The final step is for this issue creator to email [tck@eclipse.org](mailto:tck@eclipse.org) with a link to the approved issue.
