### ISSUE TITLE
MP 5.0 Review Open Issues

### ISSUE THREAD

**Issue by JanWesterkamp-iJUG** [eclipse/microprofile#275]
The included spec list is formatted differntly (as code instead of a list of links), somehow doubled and contains typos:

https://github.com/eclipse/microprofile/blob/master/spec/src/main/asciidoc/architecture.asciidoc

Typos:
Open API -> OpenAPI (the spec repo name itself has that problem too !)
Open Tracing -> OpenTracing

JWT RBAC is the spec name, but the i.e. repo is named microprofile-jwt-auth and below the name of the chapter is MicroProfile JWT Authentication 2.0 - this is inconsistent!

Can we fix the typos, format the list as in MP 4.1 and rename the repos accordingly (this need to be done in their repos of couse)?

[original message link](https://github.com/microprofile/microprofile-wg/issues/112#issuecomment-986273073)

The spec document contains an error in the following part:

MicroProfile Rest Client 3.0
MicroProfile Rest Client provides a type-safe approach for invoking RESTful services over HTTP.
The MicroProfile Rest Client builds upon the JAX-RS 2.1 APIs for consistency and ease-of-use.

The JAX-RS 2.1 APIs reference link is outdated because of the change to Jakarta RESTful Web Services!

Should be updated according to the wording and naming in the referenced spec:

Rest Client for MicroProfile
Rationale

The MicroProfile Rest Client provides a type-safe approach to invoke RESTful services over HTTP. As much as possible the MP Rest Client attempts to use Jakarta RESTful Web Services 2.1 APIs for consistency and easier re-use.

[original message link](https://github.com/microprofile/microprofile-wg/issues/112#issuecomment-986276578)

**Comment by JanWesterkamp-iJUG** [comment]
@Emily-Jiang here is the umbrella issue for my MP 5.0 review findings.

I think the best approach would be starting with a PR to fix the simple things and then create sub-issues, may be in the component specs. What do you think about it?

**Comment by Emily-Jiang** [comment]
@JanWesterkamp-iJUG please open an issue in the corresponding specs for them to be addressed. thanks

**Comment by Emily-Jiang** [comment]
I found out this issue created by Edwin to address your issue and it was solved. I am going to close this issue as a dup of #241

**Comment by JanWesterkamp-iJUG** [comment]
@Emily-Jiang: I checked @ederks85 changes and found at least one open issue regarding MP JWT - I opened an issue for that:
https://github.com/eclipse/microprofile-jwt-auth/issues/303

I will continue checking for other open aspects.
