### ISSUE TITLE
MicroProfile 6.0 Compatible Certification Request

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile#294]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  IBM
- [x] Product Name, Version and download URL (if applicable):<br/>
 [Open Liberty 22.0.0.13-beta](https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/beta/22.0.0.13-beta/openliberty-22.0.0.13-beta.zip)
- [x] Specification Name, Version and download URL:<br/>
   [MicroProfile 6.0](https://download.eclipse.org/microprofile/staging/microprofile-6.0/)
- [ ] (Optional) TCK Version, digital SHA-256 fingerprint and download URL:<br/>
n/a
- [x] Public URL of TCK Results Summary:<br/>
  [TCK Result](https://openliberty.io/certifications/microprofile/6.0/22.0.0.13-beta-TCKResults.html)
- [ ] Any Additional Specification Certification Requirements:<br/>
  n/a
- [x] Java runtime used to run the implementation:<br/>
  Java 11: IBM Semeru Runtime Certified Edition (11.0.16.1+1)
  Java 17: IBM Semeru Runtime Open Edition (17.0.4.1+1)
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
n/a
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by edbratt** [comment]
LGTM. Completed
