### ISSUE TITLE
Revisit MP Metrics

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile#296]
We need to revisit MP Metrics included in MicroProfile 6.0. MP Metrics should work closely with MP Telemetry team together with MP Fault Tolerance to evaluate the urgency to align with OTel Metrics.

https://github.com/eclipse/microprofile/pull/292

**Comment by Emily-Jiang** [comment]
@kito99 we don't have both as OpenTelemetry Metrics has not been adopted by MicroProfile as yet. The plan is to either adopt OpenTelemetry Metrics APIs or making MP APIs as facades, which heads towards that way already.

**Comment by kito99** [comment]
@Emily-Jiang  yes, I know. I guess what I'm saying is that it's strange that MP Metrics has its own API but MP Telemetry doesn't. Seems like they both should either have their own API or use OpenTelemetry.

**Comment by Emily-Jiang** [comment]
@kito99 good obeservation! The MP Telemetry uses the OpenTelemetry apis as OpenTelemetry under CNCF is a specification already. I think as for the metrics part, we can discuss further regarding our own Metrics API or adopt OpenTelemetry Metrics APIs.

**Comment by Emily-Jiang** [comment]
OpenTelemetry Metrics semantic convention is not stable as yet.
