### ISSUE TITLE
MP June Release - MP 7.0

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile#314]
**Minor updates:**
- Updating MicroProfile Telemetry - to consume the latest OpenTelemetry 
- Metrics minor update (may get pushed to 7.0) 
- Maybe update Rest Client dependency (Per Jan's review), i.e. there is a testng-dependency on the API that need to be removed 
- Review Jan's suggestions for MP platform parent pom (minor changes only)
-- [Minor update additional changes microprofile-parent#63](https://github.com/eclipse/microprofile-parent/issues/63) 

 **Breaking changes:** 
- This[ issue 295](https://github.com/eclipse/microprofile/issues/295) - need to discuss further
- [issue 296](https://github.com/eclipse/microprofile/issues/296) : Consider OpenTelemetry Metrics; discuss whether to make MP Metrics optional - June release? depends on OpenTelemetry Metrics semantic versioning.
- JWT 3 - maybe looking at what bit Jakart EE security might want to reference
- Review Jan's suggestions for MP platform parent pom (remaining major changes)

**Comment by JanWesterkamp-iJUG** [comment]
> **Minor updates:**
> 
>     * Updating MicroProfile Telemetry - to consume the latest OpenTelemetry
> 
>     * Metrics minor update (may get pushed to 7.0)
> 
>     * Maybe update Rest Client dependency (Per Jan's review), i.e. there is a testng-dependency on the API that need to be removed
> 
>     * Review Jan's suggestions for MP platform parent pom (minor changes only)
>       -- [Minor update additional changes microprofile-parent#63](https://github.com/eclipse/microprofile-parent/issues/63)
> 
> 
> **Breaking changes:**
> 
>     * This[ issue 295](https://github.com/eclipse/microprofile/issues/295) - need to discuss further
> 
>     * [issue 296](https://github.com/eclipse/microprofile/issues/296) : Consider OpenTelemetry Metrics; discuss whether to make MP Metrics optional - June release? depends on OpenTelemetry Metrics semantic versioning.
> 
>     * JWT 3 - maybe looking at what bit Jakart EE security might want to reference
> 
>     * Review Jan's suggestions for MP platform parent pom (remaining major changes)

We also need to address recent vulnerability findings - I think they are severe enough to require a patch release before.

- https://bugs.eclipse.org/bugs/show_bug.cgi?id=581579
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=581586

The equivalent issues, derived from Jakarta EE:
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=581580
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=581588

**Comment by JanWesterkamp-iJUG** [comment]
The JPMS support requirement in Jakarta EE 11 (Release Plan) has impact on MP and need to be addressed, when combined implmentations should support it.

The current dependency issues i.e. with circular dependencies or modul loading must be fixed.
