### ISSUE TITLE
MicroProfile 6.0 Compatible Certification Request - Open Liberty 23.0.0.3

### ISSUE THREAD

**Issue by jhanders34** [eclipse/microprofile#318]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  IBM

- [x] Product Name, Version and download URL (if applicable):<br/>
  [Open Liberty 23.0.0.3](https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/23.0.0.3/openliberty-microProfile6-23.0.0.3.zip)

- [x] Specification Name, Version and download URL:<br/>
   [MicroProfile 6.0](https://download.eclipse.org/microprofile/microprofile-6.0/)

- [x] (Optional) TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  n/a

- [x] Public URL of TCK Results Summary:<br/>
  [TCK Result](https://openliberty.io/certifications/microprofile/6.0/23.0.0.3-TCKResults.html)

- [x] Any Additional Specification Certification Requirements:<br/>
  No

- [x] Java runtime used to run the implementation:<br/>
  Java 11: IBM Semeru Runtime Open Edition (11.0.17+8)
  Java 17: IBM Semeru Runtime Open Edition (17.0.5+8)

- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  See the TCK results for details

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).

- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by Emily-Jiang** [comment]
Accept this issue (fall into 2-week laze consensus)
