### ISSUE TITLE
MicroProfile 6.0 Compatible Certification Request - Launcher 5.0

### ISSUE THREAD

**Issue by kosakak** [eclipse/microprofile#359]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  [Fujitsu Limited](https://www.fujitsu.com/)
- [x] Product Name, Version and download URL (if applicable):<br/>
  [Launcher 5.0](https://github.com/fujitsu/launcher/releases/tag/5.0)
- [x] Specification Name, Version and download URL:<br/>
  [MicroProfile 6.0](https://github.com/eclipse/microprofile/releases/tag/6.0)
- [x] Public URL of TCK Results Summary:<br/>
  [TCK results summary](https://github.com/fujitsu/launcher/releases/download/5.0/tck-results.html)
- [x] Any Additional Specification Certification Requirements:<br/>
    * The skipped tests in MicroProfile Rest Client come from the ReactiveStreamsPublisherTest, which is an optional spec that Launcher 5.0 does not support.
    * A challenge has been raised against the OpenAPI 3.1 TCK here: https://github.com/eclipse/microprofile-open-api/issues/557
        * The PR fixing the challenge has been approved here: https://github.com/eclipse/microprofile-open-api/pull/559
        * Our result has been applied the same fix as the one in the above PR.
- [x] Java runtime used to run the implementation:<br/>
  OpenJDK 17.0.6
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Red Hat Enterprise Linux 8.6
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by kazumura** [comment]
Accepted by 2 weeks lazy consensus.

**Comment by rstjames** [comment]
I added to Compatible 6.0 page. https://microprofile.io/compatible/6-0/
