### ISSUE TITLE
MicroProfile 4.1 Compatible Certification Request - flyingserver-mp-v3.5.0

### ISSUE THREAD

**Issue by zhangzhende** [eclipse/microprofile#360]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
    AsiaInfo
- [x] Product Name, Version and download URL (if applicable):<br/>
    [flyingserver-mp-v3.5.0](http://www.antdb.net/flyingserver)
- [x] Specification Name, Version and download URL:<br/>
   MicroProfile 4.1
- [x] (Optional) TCK Version, digital SHA-256 fingerprint and download URL:<br/>
    n/a
- [x] Public URL of TCK Results Summary:<br/>
    [flyingserver MicroProfile 4.1 TCK Result](https://github.com/AsiainfoAnhui/aisware_flyingserver_v2_ee8/blob/master/MicroProfile/TCK_result/mp4.1/TCK_Result.MD)
- [x] Any Additional Specification Certification Requirements:<br/>
    No
- [x] Java runtime used to run the implementation:<br/>
    java8 (OpenJDK Runtime Environment (build 1.8.0_372-b07))
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
    ubuntu-20.04.4
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by rstjames** [comment]
@zhangzhende could you please tell me what the java versions this is for? And do you have a download link?

**Comment by zhangzhende** [comment]
> @zhangzhende could you please tell me what the java versions this is for? Java8? And do you have a download link?

Java8, and i forgot the download link. i am sorry,maybe my package name gives some message for you :java-1.8.0-openjdk-portable-1.8.0.372.b07-1.portable.jdk.el.x86_64.tar.xz

**Comment by rstjames** [comment]
@zhangzhende thanks for the java version. Not sure what I should do with :java-1.8.0-openjdk-portable-1.8.0.372.b07-1.portable.jdk.el.x86_64.tar.xz? Do you have a link I can connect to the download button?

**Comment by zhangzhende** [comment]
> @zhangzhende thanks for the java version. Not sure what I should do with :java-1.8.0-openjdk-portable-1.8.0.372.b07-1.portable.jdk.el.x86_64.tar.xz? Do you have a link I can connect to the download button? <img alt="Screenshot 2023-08-01 at 10 51 16" width="1424" src="https://user-images.githubusercontent.com/12132146/257459773-4dbd14a6-f6a0-4587-b84e-5b615ad36ddb.png">

yes,and the link is: http://www.antdb.net/flyingserver 
thanks a lot

**Comment by zhangzhende** [comment]
> @zhangzhende thanks for the java version. Not sure what I should do with :java-1.8.0-openjdk-portable-1.8.0.372.b07-1.portable.jdk.el.x86_64.tar.xz? Do you have a link I can connect to the download button? <img alt="Screenshot 2023-08-01 at 10 51 16" width="1424" src="https://user-images.githubusercontent.com/12132146/257459773-4dbd14a6-f6a0-4587-b84e-5b615ad36ddb.png">

could you please change the logo and the name in the picture? The name is AISWare FlyingServer， and the logo is :https://github.com/AsiainfoAnhui/aisware_flyingserver_v2_ee8/blob/master/AISWare%20FlyingServer%20Logo.svg .
thank you very much

**Comment by rstjames** [comment]
@zhangzhende Sorry for the mix up with the logo. Confused two different tickets. 
<img width="1415" alt="Screenshot 2023-08-02 at 10 30 14" src="https://github.com/eclipse/microprofile/assets/12132146/bbfe18eb-8fad-4c1c-b3c4-4020c9210da4">

**Comment by zhangzhende** [comment]
@rstjames thank you very much ! !
