### ISSUE TITLE
Reference to Json-B incorrect

### ISSUE THREAD

**Issue by Daniel-Dos** [eclipse/microprofile#39]
When declaring Microprofile 2.0 in pom.xml the same accuse that it can not download the Json-B jar.

the following PR #37 corrects this small problem.

**Comment by kwsutter** [comment]
Thanks, @Daniel-Dos, for finding and reporting this problem.  We'll re-release MP 2.0 as MP 2.0.1 to correct this issue.

**Comment by Daniel-Dos** [comment]
your welcome @kwsutter .   :  )

**Comment by Daniel-Dos** [comment]
close issue. 

fix in #37 .
