### ISSUE TITLE
Update the top-level microprofile information with current Eclipse information

### ISSUE THREAD

**Issue by kwsutter** [eclipse/microprofile#4]
This top-level microprofile repo will most likely be our common portal into MicroProfile.  The content in the README is out of date, along with several of the SUMMARY.adoc references.  This issue isn't meant to fix everything, but at least resolve the gross omissions or errors.

**Comment by mikecroft** [comment]
I originally did the README as an example of the sort of thing that could be held in a documentation repo, so feel free to change as much as is needed.

Might be worth casting your eye over the FAQ, too, there's some stuff in there that should probably be verified by other people!

**Comment by kwsutter** [comment]
Yes, I was reviewing all of the docs in the MicroProfile repo...  We have
some conflicts on our merges...  Maybe we should just merge one of the PRs
and then adjust the other one with the updates?  I'm not sure the easiest
route.

**Comment by kwsutter** [comment]
Resolved with PR #8
