### ISSUE TITLE
[Architecture board] Are EE spec dependencies also transient dependencies in MP? 

### ISSUE THREAD

**Issue by OndrejM** [eclipse/microprofile#44]
It was raise here that it's not clear whether JAXB is an MP dependency or not: https://github.com/eclipse/microprofile-open-api/issues/233

Since JAXB is required by JAX-RS, it implies that MP also requires it. However, teh MP spec doesn't include JAXB while it includes Common Annotations. 

We should clarify whether transitive dependencies of EE specs are also dependencies of MP or not. If yes, then we should list all of them in the MP spec document to avoid confusion. If not, we should clarify that too.

**Comment by struberg** [comment]
I think we explicitly added JSON-B 1.0 as requirement for MP-2.0.
In MP-1.x it is indeed not required.

**Comment by kenfinnigan** [comment]
In today's architecture meeting there was agreement that this issue can now be closed
