### ISSUE TITLE
[Architecture board] Should default interface methods be avoided in MP APIs ?

### ISSUE THREAD

**Issue by OndroMih** [eclipse/microprofile#45]
@rmannibucau raised a concern about using default methods in the MP OpenAPI spec: https://github.com/eclipse/microprofile-open-api/issues/223

I think it should be discussed at a higher level because default methods are too general to discuss them only for MP OpenAPI spec. @rmannibucau raised the following concerns:

* not using any implementation in some cases and therefore a wrong behavior. It should load a provider and delegate to it the execution instead.
* from an implementation perspective what do you do if you hit a default method (on a listener) without implementation? call it? This is not what do some specs (which prefer to throw an exception to avoid to let the user think it is working as expected silently)
* it is not proxy friendly since the default will not be handled. This is more a limit case but also something to keep in mind when designing an API

Some arguments for using default methods:

* use them on a listener so that implementations don't have to implement all methods
* decrease the amount of listener interfaces - multiple interfaces can be combined to one while unimportant methods don't have to be implemented

**Comment by rmannibucau** [comment]
To think about:

    use them on a listener so that implementations don't have to implement all methods

You can drop the old adapter pattern with java 8 using CDI events and lambdas:

    onEvent(@Observes SpecStartedEvent event) {
        event.registerFilter()
            .withRootFilter(root -> {})
            .withPathFilter(path -> {})
            .withXXX(x -> {});
    }

**Comment by OndrejM** [comment]
I don't think that CDI events are required. The existing interface can just define a method with a SpecStartedEvent. However, I agree that adding `@Observes` to the argument easily registers the listener and avoids custom registration magic which is specified for [OASFilter](https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/OASFilter.java) in MP OpenAPI

**Comment by xstefank** [comment]
In LRA we've hit similar question - our use-case is based on the use of timeout for starting and joining LRA.  The spec will define what timeout value should be used to indicate to the implementation that the timeout should not be applied (currently decided value is 0). 

```java
URL startLRA(String clientID, Long timeout, ChronoUnit unit) GenericLRAException;
```

This interface will be used by end users so my intention is really just usability - if user doesn't want to explicitly set the timeout, no timeout will be used. In my opinion, I don't see any compelling reason why any implementation would do such overloading in any other way than calling this original method but of course anyone is always allowed to override default implementation of the method.

**Comment by Emily-Jiang** [comment]
I see default method is a nice way to ensure backward compatibility or a convenient way to provide a common impl. These methods can be overridden though. I don't see a big issue for this. I have not found any evidence of avoiding default method.

**Comment by rmannibucau** [comment]
@Emily-Jiang small note that if you start to put implementations in an "API" module you break the design of the spec where no impl except the SPI loading of the provider must be provided - otherwise vendors are locked which is not the goal of a spec.

The main issue with defaults is when the impl is "throw XXX" or the incompatibility with java proxying and tons of user libs/integration use that cause the spec provide interface and it is convenient for a lot of usages (auditing, enrichment etc) to just use a java lang proxy to add features. This is a real blocker until java language itself fixes it and re-enable spec to use that for trivials things.

**Comment by kenfinnigan** [comment]
Discussed in the Architecture call today.

We decided to leave it up to a spec to determine whether they are happy with maintenance cost of default methods on an interface

**Comment by rmannibucau** [comment]
@kenfinnigan just a note to not forget the cost of default method is NOT in the spec maintener hands but in implementations + users hands, this is where it breaks.
