### ISSUE TITLE
CDI and JAX-RS component models

### ISSUE THREAD

**Issue by NottyCode** [eclipse/microprofile#49]
JAX-RS has its own component model, you can make them integrate, but it is a choice the developer has to make, rather than automatic. In a MicroProfile context I think we should define tighter integration between CDI and JAX-RS. For example I believe we should say that a JAX-RS resource class has a default CDI scope of RequestScope. So if you are in MicroProfile runtime you get CDI and JAX-RS integration without having to define additional CDI annotations on the resource class.

There maybe other ways to integrate these two to play better out of the box.

**Comment by kenfinnigan** [comment]
We discussed this issue at the Architecture meeting this week and all agreed that it made sense to require all JAX-RS Resource classes that don't have a CDI scope defined, to automatically be set to be `@RequestScoped`.

This will need to be added to the umbrella spec and TCK.

**Comment by kenfinnigan** [comment]
This was discussed again in today's architecture call.

As there is now no agreement on taking the approach of setting a JAX-RS Resource to be `@RequestScoped` it needs further discussion. However, that discussion will occur on #50
