### ISSUE TITLE
Include Config 1.4

### ISSUE THREAD

**Issue by kwsutter** [eclipse/microprofile#66]
As Config 1.4 makes progress, update the MicroProfile pom.xml file with the appropriate dependency information.  This issue will be used to track the progress of including Config 1.4.

[MicroProfile Config 1.4 milestone](https://github.com/eclipse/microprofile-config/milestone/7)
[MicroProfile Config 1.4 diff](https://github.com/eclipse/microprofile-config/compare/1.3...master)

**Comment by Emily-Jiang** [comment]
I have therefore removed the MP 2.2 milestone.

**Comment by kenfinnigan** [comment]
Milestone: https://github.com/eclipse/microprofile-config/milestone/7

cc @Emily-Jiang

**Comment by jclingan** [comment]
Included.
