### ISSUE TITLE
Include Rest Client 1.2

### ISSUE THREAD

**Issue by kwsutter** [eclipse/microprofile#70]
As Rest Client 1.2 makes progress, update the MicroProfile pom.xml file with the appropriate dependency information.  This issue will be used to track the progress of including Rest Client 1.2.

**Comment by pavolloffay** [comment]
@andymc12 @kenfinnigan  when are you going to cut the final release? 

We have made progress in OT spec and now waiting for the final 1.2 release.

**Comment by andymc12** [comment]
@pavolloffay we still have one work item (propagating HTTP headers - issue [73](https://github.com/eclipse/microprofile-rest-client/issues/73) ) to complete (I'm currently working on that).  Once that is reviewed and merged, then we can cut a release candidate. I'm targeting end of the week for a release candidate - and assuming no major issues with it, then next week we should be able to publish the final release.

**Comment by pavolloffay** [comment]
Hi @andymc12 When do you plan to cut the final 1.2? I have seen https://github.com/eclipse/microprofile-rest-client/releases/tag/1.2 but the artifact is not in central.

**Comment by andymc12** [comment]
Hi @pavolloffay - I've submitted the release - just waiting for the binaries to be available on the Maven servers before announcing.  It's been almost 24 hours, so hopefully they will be available soon...
