### ISSUE TITLE
Include Metrics 2.0

### ISSUE THREAD

**Issue by kwsutter** [eclipse/microprofile#71]
As Metrics 2.0 makes progress, update the MicroProfile pom.xml file with the appropriate dependency information.  This issue will be used to track the progress of including Metrics 2.0.

**Comment by OndroMih** [comment]
@kwsutter, based on the recent decision to include new major versions of APIs in a June MP release every year, this one should target the June release (MP 2.3 / MP 3.0 release), right?

**Comment by kwsutter** [comment]
@OndroMih For integrating into the Platform release, that is correct.  But, I think the Metrics team would still like to release a Metrics 2.0 that coincides with the MP 2.2 release -- a standalone release.  In order to track that effort, I would like to leave this Issue where it is.

**Comment by kwsutter** [comment]
Based on the "breaking change" discussion, I will move this Issue to the MP 2.3/3.0 milestone.  As is being discussed, Metrics 2.0 can still be produced prior to MP 2.3/3.0, but it will be considered part of MP 2.2.

**Comment by kenfinnigan** [comment]
To clarify, you missed a "not" in there when referring to MP 2.2 right?

**Comment by kwsutter** [comment]
Expected updates for each component are to the top-level microprofile pom.xml and the associated spec documents in the src/main/asciidoc directory:  architecture.asciidoc and required-apis.asciidoc.  Thanks!

**Comment by kwsutter** [comment]
Done.
