### ISSUE TITLE
Include OpenTracing 1.3

### ISSUE THREAD

**Issue by kwsutter** [eclipse/microprofile#72]
As Open Tracing 1.3 makes progress, update the MicroProfile pom.xml file with the appropriate dependency information.  This issue will be used to track the progress of including Open Tracing 1.3.

**Comment by pavolloffay** [comment]
The first RC has been produced: https://projects.eclipse.org/projects/technology.microprofile/releases/opentracing-1.3

@kwsutter is it mandatory for MP components to create a release under https://projects.eclipse.org/projects/technology.microprofile/releases/opentracing-1.3 and schedule a review? I have noticed that not all modules are doing so.

**Comment by pavolloffay** [comment]
@fmhwong could you please review the release?

**Comment by pavolloffay** [comment]
FYI OpenTracing 1.3 has been released. There is a PR to update maven artifacts #81.
