### ISSUE TITLE
Include LRA 1.0 (stand alone)

### ISSUE THREAD

**Issue by kwsutter** [eclipse/microprofile#74]
As Long Running Actions 1.0 makes progress, update the MicroProfile pom.xml file with the appropriate dependency information.  This issue will be used to track the progress of including LRA 1.0.

Still an open question whether to include LRA as a MP platform requirement, or an optional aspect of the platform.

**Comment by mmusgrov** [comment]
It is unlikely that we will have a release ready for version 2.2 of the platform which gives us more time to debate whether LRA needs to be a mandatory. Once the spec becomes clear it should be easier to make that decision.

**Comment by kwsutter** [comment]
Thanks, @mmusgrov.  Do you think LRA 1.0 will be available standalone by Feb 2019?  If that's doable, then we can leave LRA 1.0 on the Milestone and continue to drive towards that goal.  It would still be nice to announce MP 2.2 with LRA 1.0 (and any other standalone specs) at the same time...  But, if that's not looking promising, then I can just remove the Milestone and Project tags (or move them to the June release).

**Comment by mmusgrov** [comment]
I will put it on the Agenda for the next MP LRA hangout but personally I think we still have too many unresolved issues and the June deadline is the more likely one.

Also, does standalone simply mean that the spec is optional?

**Comment by kwsutter** [comment]
@mmusgrov We as a community decided that all brand new 1.0 specs should be released standalone first (outside of the MicroProfile platform).  This allows for some potential client usage and feedback before considering it to be included in the platform.  It also allows for a more flexible schedule so that standalone releases don't necessarily have to stick with the platform release schedule.

I will wait for the conclusion from your hangout before we move this item to the MP 2.3 milestone.  Thanks!

**Comment by mmusgrov** [comment]
The opinion was that there is a possibility of having a standalone version ready for Feb provided we can keep working on the spec up until the 2.2 release in Feb. Personally I think it is 50/50 so what would be the consequence of us not hitting that date?

**Comment by kwsutter** [comment]
@mmusgrov I don't think there are any consequences of not meeting the Feb MP 2.2 deadlines.  We're a very agile organization and we ship when things are ready.  Since LRA 1.0 is a standalone feature, there is no big push for the MP 2.2 dates.  Given your status and from what I hear from the IBM team, it sounds like maybe we should just move this Issue to the MP 2.3 milestone.  You can either do it, or give me the green light to move it.  Thanks.
