### ISSUE TITLE
Incorporate jakarta.* maven artifacts instead of javax.* artifacts

### ISSUE THREAD

**Issue by kwsutter** [eclipse/microprofile#83]
Currently, we have listed dependencies against the javax.* artifacts in Maven for our Java EE 8 dependencies.  Now that the jakarta.* artifacts are in Maven in support of Jakarta EE 8, should we change our dependencies?  If so, when?

To be clear, this is for the following dependencies:  (We would only do this for MicroProfile 2.x since only Java EE 8 contents were transferred to Eclipse.)
- CDI 2.0 -> 2.0.1
- JAX-RS 2.1 -> 2.1.4
- JSON-P 1.1 -> 1.1.5
- JSON-B 1.0 -> 1.0.1
- Common Annotations 1.3 -> 1.3.4

The content and functionality of these jakarta.* dependencies have to be the same as their corresponding javax.* parts (this is required to allow for Java EE 8 compliance in Eclipse).  The java package names are not changing.  This is just for the maven coordinates in the pom.xml files.

[Example for CDI 2.0.1...](https://mvnrepository.com/artifact/jakarta.enterprise/jakarta.enterprise.cdi-api/2.0.1)

Current:
```
        <dependency>
            <groupId>javax.enterprise</groupId>
            <artifactId>cdi-api</artifactId>
            <version>2.0</version>
        </dependency>

```
Proposed:
```
        <dependency>
            <groupId>jakarta.enterprise</groupId>
            <artifactId>javax.enterprise.cdi-api</artifactId>
            <version>2.0.1</version>
        </dependency>

```

When we make this change, it should get applied to the Platform pom.xml as well as the individual Component pom.xml files.

**Comment by kenfinnigan** [comment]
As we're currently "Java EE 8", is there any advantage to switching to "Jakarta EE 8" instead of waiting for "Jakarta EE 9"?

**Comment by rdebusscher** [comment]
No real advantage except some moral support for the Jakarta EE work which
has done.

We can do this together with the June release. This will already be a
breaking change release so can go along nicely
MP 1.x -> Java EE 7
MP 2.x -> Java EE 8
MP 3.x -> Jakarta EE 8
MP x.x -> Jakarta EE 9

Rudy

**Comment by kenfinnigan** [comment]
But is Jakarta EE 8 actually "a thing"?

My understanding is that though the APIs have been re-released for each specification, there isn't a top level specification release for Jakarta EE 8.

**Comment by kwsutter** [comment]
Agree, @kenfinnigan.  The more I thought about this, the less that I think we have work to do...  Our MicroProfile implementations could still eventually claim Jakarta EE compliance, even if our dependencies are still referencing the original Java EE artifacts.  So, maybe until we want to claim support for Jakarta EE 9, maybe there's nothing to do???

FYI, eventually there will be a "Jakarta EE 8".  The Jakarta EE Steering and Spec Committees are currently working through that definition.   We need to define the TCK process, the branding process, the Spec process, etc.  But, once we get all of that in place, Jakarta EE 8 will be "a thing".

**Comment by kenfinnigan** [comment]
I think maybe either wait for Jakarta EE 8 spec to have a release, or Jakarta EE 9

**Comment by anunnakian** [comment]
I think this issue is deprecated @kwsutter

**Comment by Emily-Jiang** [comment]
done
