### ISSUE TITLE
Include of EJB on Microprofile

### ISSUE THREAD

**Issue by rhuan080** [eclipse/microprofile#92]
Hi,

EJB is a good technology that promotes solutions to several problems about distributed system. It has MDB to consume queue, EJB timer, good integration with JPA and JTA. I think the EJB is a important Java EE spec that can be supported by Microprofile. I guess some Java EE/Jakarta EE specs like JPA and JTA will participate of Microprofile umbrella in the future. With this, EJB make sense to be included into Microprofile umbrella.

Thank you
Rhuan Rocha

**Comment by kenfinnigan** [comment]
I believe the rationale for going with CDI from day one was to focus on that programming model, as opposed to Java EE that had several different programming models.

If all these pieces of EJB are present in Java EE and Jakarta EE, what is the advantage to bringing them into MicroProfile?

**Comment by GedMarc** [comment]
Field injection only has so much of a lifespan left, in keeping a quick forward motion, that will be supported in the future with future JPMS modular development, CDI doesn't have much place there.

Jakarta EE is purely there to support and allow the what-will-be legacy architecture. EE was cancelled for good reason.

Please do not consider this.

**Comment by rhuan080** [comment]
Hi,

@kenfinnigan, We don't have a formal description of how Microprofile specs should behave with EJB mechanism. What's the behave when we use Fault Tolerance with EJB? Create a formal description of how to Microprofile spec should behave with EJB is important, because EJB works with several specs of Java EE and Jakarta EE. 

EJB can be used to same tasks of Reactive System, because we can use MDB to consume Kafka and other queue system. In my understanding, when we have same spec inside Microprofile umbrella, we guarantee that this spec have compatibility with Microprofile ecosystem.

**Comment by kenfinnigan** [comment]
Though EJB, or anything from Java EE/Jakarta EE, could be used with MicroProfile, MicroProfile only defines the integration with parts of those specifications where it feels the integration is critical to microservice development in the cloud.

I don't see providing how MicroProfile specifications integrate with EJB to be something that we would do.

**Comment by pilhuhn** [comment]
@rhuan080 I believe that what you are asking is better placed into the JakartaEE spec process going forward. There are unfortunately still too many unknowns so that I can't give you a direct pointer.

**Comment by kenfinnigan** [comment]
We discussed this in today's MP Architecture call and agreed that EJB doesn't add enough value for inclusion in MicroProfile. There was also concern about introducing another programming model in addition to what we already have, CDI.

@rhuan080, if there are aspects to the EJB specification that you don't consider to be covered by CDI, please raise it in a new thread to the Google Group. @antoinesd and @Emily-Jiang felt there might be some misconceptions about gaps that aren't actually gaps, so the plan is to write a blog post explaining how EJB features can be mapped to CDI and MicroProfile. If you have areas that aren't present in CDI, raising it to them will enable them to include discussion of those topics in the blog.
