### ISSUE TITLE
Rename microprofile-concurrency github project to microprofile-context-propagation

### ISSUE THREAD

**Issue by njr-11** [eclipse/microprofile#97]
Per the decision that was reached under https://github.com/eclipse/microprofile-concurrency/issues/142 
the MicroProfile Concurrency specification is being renamed to the MicroProfile Context Propagation specification, and therefore the github project must be renamed to reflect this (along with other rename changes being covered under other pulls).
We do not have the admin permission that is necessary to rename the github project ourselves, so I am opening this issue so that someone with this authority can do so.

After this change, the project found here,
https://github.com/eclipse/microprofile-concurrency

Should be renamed to,
https://github.com/eclipse/microprofile-context-propagation

**Comment by eclipsewebmaster** [comment]
Done.

**Comment by njr-11** [comment]
It looks like the gitter chat will also need an update from,
https://gitter.im/eclipse/microprofile-concurrency
to
https://gitter.im/eclipse/microprofile-context-propagation

Would it be correct to open an issue for that in this repo? Or is there somewhere else to request?
