### ISSUE TITLE
How to communicate breaking changes

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile#99]
As Metrics spec, Health Check, Open API are introducing breaking breaks, we need to establish a common rule to announce break changes.

e.g. Add a section on what the break changes are and migrate plan on how to fix the compilation or other related issues due to the break changes.

We need to set up a rule and stick to that to be consistent.

**Comment by kenfinnigan** [comment]
I think we've added the necessary doc updates as to how this needs to be done
